### ISSUE TITLE
Using `before = true` doesn't return the expected data structure.

### ISSUE THREAD

**Issue by cerinoligutom** [olavim/objection-cursor#11]
The returned data is the snippet below when using `previousCursorPage()`

```js
{
  results: {
    results: [
      // model results
    ],
    pageInfo: {
      // page info properties
    }
}
```

It seems to be working fine when using `nextCursorPage()`

```js
{
  results: [
    // model results
  ],
  pageInfo: {
    // page info properties
  }
}
```

**Comment by olavim** [comment]
Thank you for making an issue. Sorry for taking so long to answer.

This should be tested pretty extensively. See https://github.com/olavim/objection-cursor/blob/master/test/cursor.js#L122, for example.

Could you show me code that is giving you the wrong response structure? Also, which version of Objection are you using?

**Comment by olavim** [comment]
Closing as stale

**Comment by cerinoligutom** [comment]
> Thank you for making an issue. Sorry for taking so long to answer.
> 
> This should be tested pretty extensively. See https://github.com/olavim/objection-cursor/blob/master/test/cursor.js#L122, for example.
> 
> Could you show me code that is giving you the wrong response structure? Also, which version of Objection are you using?

Sorry for getting back late, a coworker was having the issue previously. Not quite sure what's their course of action for it but seems like they've resolved it.
