### ISSUE TITLE
hasPreviouse returning true on first query

### ISSUE THREAD

**Issue by oscaroox** [olavim/objection-cursor#13]
When my data amount exceeds the default limit of 50, hasPreviouse returns true.

It seems that the third query that fetches additional page info uses the default limit 50 instead of my own set limit.

query for results using my limit of 10

![query-results](https://user-images.githubusercontent.com/6206624/73604352-b5259380-458f-11ea-998d-095ac9a54fe3.png)

third query using  limit of 50 to calculate remaining, hasNext ....
![query-info](https://user-images.githubusercontent.com/6206624/73604353-b9ea4780-458f-11ea-947d-f15fa0fe7318.png)

steps to reproduce

plugins settings
```js
 cursorMixin({
      limit: 50,
      pageInfo: {
          total: true,
          hasNext: true,
          hasPrevious: true,
      },
 }),
````
Insert more than the limit
```js
const users = [...Array(60)].map(() =>
  UserModel.query().insert({
     firstName: faker.name.firstName(),
     balance: faker.random.number({ min: 1200, max: 4500 }),
  }),
);
await Promise.all(users);
```
get the first 10 items
```js
const users = await UserModel.query()
    .orderBy('id')
    .limit(10)
    .cursorPage();

expect(users.pageInfo.hasNext).toBeTruthy(); // returns true
expect(users.pageInfo.hasPrevious).toBeFalsy(); // also returns true

```

**Comment by olavim** [comment]
Thanks for the issue. This should be fixed in version 1.0.1
