### ISSUE TITLE
Does not work with objection 2

### ISSUE THREAD

**Issue by oscaroox** [olavim/objection-cursor#15]
The returned pageInfo with hasPrevious and hasNext doesnt work in version 2.
At the end of the page it still returns hasNext true and hasPrevious false

I will try to create a pull request if I get the time this week. But this will most likely be a breaking change.

**Comment by olavim** [comment]
Ah, I didn't realize to try v2 when I pushed my previous fix. This is fixed now in 1.0.2. Tested with versions `0.9.4`, `1.6.11`, `2.1.2`. No breaking changes fortunately 🙏
