### ISSUE TITLE
order by is gone when mix where and whereRaw, select and selectRaw together

### ISSUE THREAD

**Issue by michellechsy** [olavim/objection-cursor#5]
Our query is complex, which includes joining several tables, and conditions may cover all the tables (depends on what user provides), which looks like: 
`
Model.query().select(<table fields>).select(Model.knex().raw(`CASE WHEN xxxxxxxx`)).where(xxx).whereRaw(`xxx`).orderBy(xxxx)
`
1. When querying without any conditions, i.e. no 'where' clause above, pagination works well
2. When querying with conditions, e.g. a whereRaw in above query, pagination is incorrect, and according to the printout, the 'order by' was gone, `remaining` in the result 'pageInfo' is incorrect either (1-10, 7-16, and then even i click go 'previous', it still goes to 26-36)

**Comment by olavim** [comment]
I couldn't reproduce this by just using `select`, `select(<raw query>)`, `where`, and `whereRaw` with my test data. Could you give me the exact query you use, or better yet, a repository with failing code.

**Comment by olavim** [comment]
Please try version `1.0.0-alpha.1`. The release includes a couple of fixes which *might* solve your issues.

**Comment by olavim** [comment]
@michellechsy are you still having issues?
